name: ekmek_teknesi
description: "Anneniz için ekmek sipariş yönetimi uygulaması."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  sqflite: ^2.3.3
  path: ^1.9.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  # GÜNCELLENDİ: file_saver kaldırıldı, share_plus eklendi.
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/foreground_icon.png" # Eklendi
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/foreground_icon.png # Eklendi
